import './globals.css'
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic'
import { Suspense } from 'react'
import Loading from './loading'

const ToastContainerClient = dynamic(() => import('@/components/Notification'), { ssr: false })
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'My Profile',
    description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en'>
            <body className={`${inter.className} relative bg-gradient-bg max-h-screen overflow-y-scroll`}>
                <Suspense fallback={<Loading />}>{children}</Suspense>
                <div className='deep-shadow-blur'></div>
                <ToastContainerClient />
            </body>
        </html>
    )
}
